#!/usr/bin/python

"""Amulet tests on a basic mysql deployment on precise-icehouse."""

from basic_deployment import MySQLBasicDeployment

if __name__ == '__main__':
    deployment = MySQLBasicDeployment(series='precise',
                                           openstack='cloud:precise-icehouse',
                                           source='cloud:precise-updates/icehouse')
    deployment.run_tests()
