#!/usr/bin/python

"""Amulet tests on a basic mysql deployment on trusty-juno."""

from basic_deployment import MySQLBasicDeployment

if __name__ == '__main__':
    deployment = MySQLBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-juno',
                                           source='cloud:trusty-updates/juno')
    deployment.run_tests()
