#!/usr/bin/python

"""Amulet tests on a basic mysql deployment on trusty-kilo."""

from basic_deployment import MySQLBasicDeployment

if __name__ == '__main__':
    deployment = MySQLBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-kilo',
                                           source='cloud:trusty-updates/kilo')
    deployment.run_tests()
