#!/usr/bin/python

"""Amulet tests on a basic mysql deployment on wily-liberty."""

from basic_deployment import MySQLBasicDeployment

if __name__ == '__main__':
    deployment = MySQLBasicDeployment(series='wily')
    deployment.run_tests()
