#!/bin/bash

set -ex

sudo add-apt-repository --yes ppa:juju/stable
sudo apt-get update --yes
sudo apt-get install --yes python-amulet \
                           python-keystoneclient

# Enable http proxy if AMULET_HTTP_PROXY is set
if [[ -n "$AMULET_HTTP_PROXY" ]]; then
  export HTTP_PROXY=$AMULET_HTTP_PROXY
  export HTTPS_PROXY=$(echo $AMULET_HTTP_PROXY | sed 's/http/https/g')
  echo " + Enabling HTTP(S) proxies."
  env | grep PROXY
fi

# Setup for generic amulet test (Not in main < Vivid, pip it instead)
#sudo apt-get install python3-pymysql
sudo pip install PyMySQL3
