#!/usr/bin/python

"""Amulet tests on a basic mysql deployment on trusty-icehouse."""

from basic_deployment import MySQLBasicDeployment

if __name__ == '__main__':
    deployment = MySQLBasicDeployment(series='trusty')
    deployment.run_tests()
