#!/usr/bin/python

"""Amulet tests on a basic mysql deployment on utopic-juno."""

from basic_deployment import MySQLBasicDeployment

if __name__ == '__main__':
    deployment = MySQLBasicDeployment(series='utopic')
    deployment.run_tests()
