#!/usr/bin/python

"""Amulet tests on a basic mysql deployment on trusty-mitaka."""

from basic_deployment import MySQLBasicDeployment

if __name__ == '__main__':
    deployment = MySQLBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-mitaka',
                                           source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
