#!/usr/bin/python

"""Amulet tests on a basic mysql deployment on trusty-liberty."""

from basic_deployment import MySQLBasicDeployment

if __name__ == '__main__':
    deployment = MySQLBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-liberty',
                                           source='cloud:trusty-updates/liberty')
    deployment.run_tests()
