#!/usr/bin/python

"""Amulet tests on a basic mysql deployment on xenial-mitaka."""

from basic_deployment import MySQLBasicDeployment

if __name__ == '__main__':
    deployment = MySQLBasicDeployment(series='xenial')
    deployment.run_tests()
