#!/usr/bin/env python3

import logging

import amulet


d = amulet.Deployment()

d.add('mysql')
d.expose('mysql')

try:
    d.setup(timeout=900)
    d.sentry.wait()
except amulet.helpers.TimeoutError:
    amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
except:
    raise

# Check root password
user = 'root'
mysql = d.sentry.unit['mysql/0']
password = mysql.file_contents('/var/lib/mysql/mysql.passwd')
logging.info('root password: ' + password)
sql_template = ("echo SELECT DISTINCT User FROM user |"
                " mysql -u {} --password={} mysql")
sql_command = (sql_template).format(user, password)
result, code = mysql.run(sql_command)
logging.debug('Execution script:' + sql_command)
logging.debug("Execution Return Code:" + str(code))
logging.debug('Execution result:' + result)
result = result.split('\n')[1:]
u = False
for r in result:
    u = u or user in r

if not u:
    amulet.raise_status(amulet.FAIL,
                        'Error connecting to mysql from localhost.')
else:
    amulet.raise_status(amulet.PASS,
                        'Connected through localhost.')
