#!/usr/bin/python3

import amulet
import mysql.connector

d = amulet.Deployment()

d.add('mysql')
d.expose('mysql')

try:
    d.setup(timeout=900)
    d.sentry.wait()
except amulet.helpers.TimeoutError:
    amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
except:
    raise

# Testing Max Connections
max_connections = 10
d.configure('mysql', {'max-connections': max_connections})
mysql_server = d.sentry.unit['mysql/0']
mysql_password = mysql.file_contents('/var/lib/mysql/mysql.passwd')

connections = []

# As we are using root as test user, we need to test with max_conn + 1
cnx_list = []
try:
    for cnx_idx in xrange(0, max_connections + 1):
        cnx = mysql.connector.connect(
            user='root',
            password=mysql_password,
            host=mysql_server.info['public-address'],
            database='mysql')

        cnx_list.append(cnx)
except mysql.connector.Error as err:
    if len(cnx_list) < max_connections + 1:
        amulet.raise_status(
            amulet.FAIL,
            'MySQL is not allowing to connect {} times.'.format(
                max_connections))

else:
    amulet.raise_status(amulet.FAIL,
                        'Max connection reached, and still able to connect.')

for cnx in cnx_list:
    cnx.close()

d.configure('mysql', {'max-connections': -1})

# Now you can use d.sentry.unit[UNIT] to address each of the units and perform
# more in-depth steps. There are three test statuses: amulet.PASS, amulet.FAIL,
# and amulet.SKIP - these can be triggered with amulet.raise_status(). Each
# d.sentry.unit[] has the following methods:
# - .info - An array of the information of that unit from Juju
# - .file(PATH) - Get the details of a file on that unit
# - .file_contents(PATH) - Get plain text output of PATH file from that unit
# - .directory(PATH) - Get details of directory
# - .directory_contents(PATH) - List files and folders in PATH on that unit
# - .relation(relation, service:rel) - Get relation data from return service

# Make sure to rename this file from something other than 00-autogen
