#!/usr/bin/python

"""Amulet tests on a basic mysql deployment on vivid-kilo."""

from basic_deployment import MySQLBasicDeployment

if __name__ == '__main__':
    deployment = MySQLBasicDeployment(series='vivid')
    deployment.run_tests()
